### ISSUE TITLE
Buy pump

### ISSUE THREAD

**Issue by dingens** [fu-ilab-swp18/pflanzen1#8]

**Comment by jarissimo** [comment]
Bought this: 
* [pump](https://www.amazon.de/gp/product/B01FTL6H8S/ref=od_aui_detailpages00?ie=UTF8&psc=1)
* [tube/hose](https://www.amazon.de/gp/product/B000H6SRM0/ref=od_aui_detailpages00?ie=UTF8&psc=1)

The pump already takes ~4.8W, I think we should not go for a bigger one for now. And the hose nearly costs as much as the pump m)
